FROM node:19
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json package.json yarn.lock .yarnrc.yml ./
COPY .yarn .yarn/

RUN yarn install
COPY . ./
# If you are building your code for production
# RUN npm ci --only=production
ARG DATABASE_URL=postgres://postgres:postgres@postgres:5432/animals
#ARG PRISMA_CLIENT_ENGINE_TYPE=dataproxy
RUN yarn  build

COPY prisma/schema.prisma ./build/schema.prisma

EXPOSE 3000
CMD [ "yarn","start" ]
